Updated feature_workflow.yaml

diff --git a/.github/workflows/feature_workflow.yaml b/.github/workflows/feature_workflow.yaml
--- a/.github/workflows/feature_workflow.yaml
+++ b/.github/workflows/feature_workflow.yaml
@@ -48,35 +48,42 @@ jobs:
         run: |
           BRANCH_NAME="${{ github.event.inputs.branch_name }}"
           if [[ $BRANCH_NAME != feature/* ]]; then
-            FEATURE_BRANCH="feature/$BRANCH_NAME"
-            echo "Renaming branch to $FEATURE_BRANCH"
-            git branch -m "$FEATURE_BRANCH"
-            git push origin -u "$FEATURE_BRANCH"
+            NEW_BRANCH_NAME="feature/$BRANCH_NAME"
+            echo "Renaming branch to $NEW_BRANCH_NAME"
+            git branch -m "$NEW_BRANCH_NAME"
+            git push origin -u "$NEW_BRANCH_NAME"
           else
+            NEW_BRANCH_NAME="$BRANCH_NAME"
             echo "Branch name already starts with feature/"
           fi
+          echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
 
       - name: Check for existing PR
         run: |
-          pr_exists=$(gh pr list --head ${{ github.event.inputs.branch_name }} --json number --jq '.[].number')
+          pr_exists=$(gh pr list --head "NEW_BRANCH_NAME" --json number --jq '.[].number')
           if [ -n "$pr_exists" ]; then
-            echo "Error: Pull Request already exists for branch ${{ github.event.inputs.branch_name }}."
+            echo "Error: Pull Request already exists for branch $NEW_BRANCH_NAME."
             exit 1
           fi
 
       - name: Update Maven coordinates
         run: |
-          VERSION="1.0.0-${{ github.event.inputs.branch_name }}-SNAPSHOT"
+          VERSION="1.0.0-${NEW_BRANCH_NAME}-SNAPSHOT"
           mvn versions:set -DnewVersion=$VERSION
           mvn versions:commit
+
+      - name: Commit Maven Version Update
+        run: |
           git add pom.xml
-          git commit -m "chore: update Maven coordinates to $VERSION"
-          git pull origin HEAD
-          git push -u origin HEAD
+          git commit -m "chore: update Maven coordinates to $VERSION" || echo "No changes to commit"
+
+      - name: Push Changes
+        run: |
+          git push origin $NEW_BRANCH_NAME
 
       - name: Create Draft PR
         run: |
-          gh pr create --head "$FEATURE_BRANCH" --base main --title "Draft PR for $FEATURE_BRANCH" --body "This is a draft PR for $FEATURE_BRANCH" --draft
+          gh pr create --head "NEW_BRANCH_NAME" --base main --title "Draft PR for $NEW_BRANCH_NAME" --body "This is a draft PR for $NEW_BRANCH_NAME" --draft
 
 
   finish-feature:
